# Generated by Django 4.2.2 on 2023-06-29 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=250)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.grade')),
            ],
        ),
    ]
