# Generated by Django 4.2.2 on 2023-06-29 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_subject'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
