# Generated by Django 4.2.2 on 2023-06-29 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='members',
        ),
        migrations.AddField(
            model_name='subject',
            name='members',
            field=models.ManyToManyField(related_name='mycourses', to=settings.AUTH_USER_MODEL),
        ),
    ]
