# Generated by Django 4.2.2 on 2023-06-29 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_subject_members_subject_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=7),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=450)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('attachment', models.FileField(upload_to='attachments')),
                ('drive', models.CharField(max_length=250)),
                ('Subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.subject')),
            ],
        ),
    ]
