# Generated by Django 4.2.2 on 2023-07-02 16:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_subject_price_lecture'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='quiz',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='attachment',
            field=models.FileField(max_length=255, upload_to='attachments', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='drive',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='mycourses', to=settings.AUTH_USER_MODEL),
        ),
    ]
