# Generated by Django 4.2.2 on 2023-07-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_alter_lecture_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='quiz',
            field=models.URLField(blank=True),
        ),
    ]
