# Generated by Django 4.2.2 on 2023-07-14 07:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_alter_lecture_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='attachment',
            field=models.FileField(blank=True, max_length=255, upload_to='attachments', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
