# Generated by Django 4.2.2 on 2023-06-27 11:27

import AlRaziAcademy.utils
import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profileImg', models.ImageField(default='profile_img/avatar.png', upload_to=accounts.models.user_directory_path, verbose_name='User Picture')),
                ('phone', models.CharField(blank=True, help_text='077 or 078 or 075', max_length=11, null=True, validators=[AlRaziAcademy.utils.validate_phone], verbose_name='Phone number')),
                ('facebook', models.URLField(blank=True, default=None, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('study', models.CharField(blank=True, max_length=11, null=True, verbose_name='Your studying Details:')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
